# Generated by Django 4.0.6 on 2022-07-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Payment Card Name')),
                ('name_on_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name on Card')),
                ('type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Type')),
                ('number', models.CharField(blank=True, max_length=19, null=True, verbose_name='Number')),
                ('security_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Security Code')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Site name')),
                ('username', models.CharField(blank=True, max_length=25, null=True, verbose_name='User name')),
                ('password', models.CharField(blank=True, max_length=25, null=True, verbose_name='Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Note name')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Account Name')),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Name')),
                ('account_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account Type')),
                ('routing_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Routing Name')),
                ('account_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account Number')),
                ('swift_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Swift Code')),
                ('iban_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Iban Number')),
                ('pin', models.CharField(blank=True, max_length=25, null=True, verbose_name='Pin')),
                ('branch_address', models.CharField(blank=True, max_length=25, null=True, verbose_name='Branch Address')),
                ('branch_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Branch Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Address name')),
                ('title', models.CharField(blank=True, choices=[('Sir', 'Adult male of any age'), ('Madam', 'Adult female of any age'), ('Mr', 'Any man'), ('Mrs', "Married woman who uses her husband's last name"), ('Ms', 'Married or unmarried woman; common in business'), ('Miss', 'Unmarried woman'), ('Dr', 'Doctor')], max_length=25, null=True, verbose_name='Formal title')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Last name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=25, null=True, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('address1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 3')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City/Town')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='County')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=5, null=True, verbose_name='ZIP/Postal Code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
