# Generated by Django 4.0.6 on 2022-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='username',
        ),
        migrations.AddField(
            model_name='password',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Mr', max_length=25, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, choices=[('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr')], default='Sir', max_length=25, null=True, verbose_name='Formal title'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Checking account', 'Checking account'), ('Saving account', 'Saving account'), ('Money market account', 'Money market account'), ('Certificate of deposite (CD) account', 'Certificate of deposite (CD) account')], default='Checking account', max_length=50, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='type',
            field=models.CharField(blank=True, choices=[('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Charge card', 'Mr'), ('Pre-paid card', 'Charge card'), ('Business travel card', 'Business travel card'), ('Purchasing card', 'Purchasing card')], default='Credit card', max_length=30, null=True, verbose_name='Type'),
        ),
    ]
