# Generated by Django 4.0.6 on 2022-07-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_password_username_password_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='address_name',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='name',
            new_name='bank_account_name',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='note_name',
        ),
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='password_name',
        ),
        migrations.RenameField(
            model_name='paymentcard',
            old_name='name',
            new_name='payment_card_name',
        ),
    ]
