# Generated by Django 4.0.6 on 2022-07-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_rename_name_address_address_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
