# Generated by Django 4.0.6 on 2022-07-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_address_user_alter_bankaccount_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Address 2'),
        ),
    ]
